baseurl = "https://ukrainer-in-trier.github.io"
metaDataFormat = "yaml"
title = "Ukrainer In Trier"
theme = "blist"

buildFuture = true

DefaultContentLanguage = "uk"
DefaultContentLanguageInSubdir = true
[languages]
    [languages.uk]
        contentDir = "content/uk" #Ukrainian
        weight = 1
        languageName = "Український"
    [languages.uk.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = " — громадська платформа, створена заради розвитку та підтримки українського культурного простору у вимушеній еміграції."
        introSubtitle2 = "Чому ми вважаємо, що це важливо?"
        introSubtitle3 = "Говорити про Україну від першої особи - місія не менш важлива, ніж робота дипломатів на найвищих рівнях. Показати європейцям, що українська війна - не клаптик зі щоденної газети, не короткий сюжет в телевізорі, а люди - живі, волелюбні, творчі та сильні. Ми вкладаємо усі свої сили, щоб підтримати боротьбу за волю та спільні демократичні цінності.."
        metaTitle = "Наша мета:"
        metaSubtitle = "Своєю діяльністю - підтримати Україну "
        metaSubtitle2 = "та не дати забути про війну "
        calendarTitle = "Календар подій"
        partnersTitle = "НАС ПІДТРИМУЮТЬ"
        partnersSubtitle ="Ми вдячні організаціям, за те що підтримують нас! За те що вірять в нашу справу і йдуть пліч-о-пліч з нами!"
        helpTitle = "Приєднуйся до нас"
        aboutButton = "Про нас"
        partnersButton = "Партнери"
        projectsButton = "Наші проекти"
        wantHelpButton = "Я хочу допомогти"
        needHelpButton = "Мені потрібна допомога"
        introPhoto = "/main-img.webp"
        logo = "/logo.svg"

    [[languages.uk.menu.main]]
        name = "Головна"
        url = "/uk/"
        weight = 1

    [[languages.uk.menu.main]]
        name = "Про нас"
        url = "/uk/about/"
        weight = 2

    [[languages.uk.menu.main]]
        identifier = "projects"
        name = "Наші проекти"
        url = "/uk/projects/"
        weight = 3

    [[languages.uk.menu.main]]
        name = "Aрт простір / мистецтво"
        url = "/uk/projects/art/"
        weight = 1 
        parent = "projects"

    [[languages.uk.menu.main]]
        name = "Кейтеринг/ Фуд-корти"
        url = "/uk/projects/catering/"
        weight = 2 
        parent = "projects"

    [[languages.uk.menu.main]]
        name = "Творчий колектив 'Вільні птахи'"
        url = "/uk/projects/free-birds/"
        weight = 3 
        parent = "projects"

    [[languages.uk.menu.main]]
        name = "Освітні проекти"
        url = "/uk/projects/educate-projects/"
        weight = 4 
        parent = "projects"

    [[languages.uk.menu.main]]
        name = "Психологічна допомога"
        url = "/uk/projects/psych-help/"
        weight = 5 
        parent = "projects"

    [[languages.uk.menu.main]]
        name = "Допомога у Трірі"
        url = "/uk/projects/trier-help/"
        weight = 6 
        parent = "projects"
    

    [[languages.uk.menu.main]]
        name = "Галерея"
        url = "/uk/gallery/"
        weight = 4

    [[languages.uk.menu.main]]
        name = "Календар"
        url = "/uk/calendar/"
        weight = 5

    [[languages.uk.menu.main]]
        identifier = "Help"
        name = "Допомога"
        url = "/uk/help"
        weight = 6

     [[languages.uk.menu.main]]
        name = "Мені потрібна допомога"
        url = "/uk/help/need-help"
        weight = 1   
        parent = "Help"
        
     [[languages.uk.menu.main]]
        name = "Хочу допомогти"
        url = "/uk/help/want-help"
        weight = 2  
        parent = "Help"

    [[languages.uk.menu.main]]
        name = "Партнери"
        url = "/uk/partners"
        weight = 7

    [[languages.uk.menu.main]]
        name = "Контакти"
        url = "/uk/contacts"
        weight = 8

    [languages.de]
        contentDir = "content/de" # Deutsch
        weight = 2
        languageName = "Deutsch"
        title = "Ukrainer in Trier"
    [languages.de.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = "- eine öffentliche Plattform zur Entwicklung und Förderung des ukrainischen Kulturraums in der Zwangsemigration."
        introSubtitle2 = "Warum halten wir das für wichtig?"
        introSubtitle3 = "Über die Ukraine aus der ersten Person zu sprechen, ist eine Mission, die nicht weniger wichtig ist als die Arbeit von Diplomaten auf höchster Ebene. Den Europäern zu zeigen, dass der Krieg in der Ukraine kein Fetzen aus einer Tageszeitung ist, keine Kurzgeschichte im Fernsehen, sondern Menschen – lebendig, freiheitsliebend, kreativ und stark. Wir tun unser Bestes, um den Kampf für Freiheit und gemeinsame demokratische Werte zu unterstützen."
        metaTitle = "Unser Ziel:"
        metaSubtitle = "Unsere Tätigkeit besteht darin, die Ukraine zu unterstützen "
        metaSubtitle2 = "und den Krieg nicht zu vergessen"
        calendarTitle = "Eventkalender"
        partnersTitle = "WIR WERDEN UNTERSTÜTZT"
        partnersSubtitle ="Wir danken den Organisationen, die uns unterstützen! Dafür, dass Sie an unsere Sache glauben und Seite an Seite mit uns gehen!"
        helpTitle = "Begleiten Sie uns"
        aboutButton = "Über uns"
        partnersButton = "Partner"
        projectsButton = "Unsere Projekte"
        wantHelpButton = "Ich will helfen"
        needHelpButton = "Ich brauche Hilfe"
        introPhoto = "/main-img.webp"
        logo = "/logo.svg"

    [[languages.de.menu.main]]
        name = "Hauptseite"
        url = "/de/"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über uns"
        url = "/de/about"
        weight = 2

    [[languages.de.menu.main]]
        identifier = "projects"
        name = "Unsere Projekte"
        url = "/de/projects/free-birds/"
        weight = 3

    [[languages.de.menu.main]]
        name = "Kunstraum / Kunst"
        url = "/de/projects/art/"
        weight = 1 
        parent = "projects"


    [[languages.de.menu.main]]
        name = "Catering/ Foodcourts"
        url = "/de/projects/catering/"
        weight = 2 
        parent = "projects"

    [[languages.de.menu.main]]
        name = "Kreativteam 'Free Birds'"
        url = "/de/projects/free-birds/"
        weight = 3 
        parent = "projects"

    [[languages.de.menu.main]]
        name = "Bildungsprojekte"
        url = "/de/projects/educate-projects/"
        weight = 4 
        parent = "projects"

    [[languages.de.menu.main]]
        name = "Psychologische Hilfe"
        url = "/de/projects/psych-help/"
        weight = 5 
        parent = "projects"

    [[languages.de.menu.main]]
        name = "Hilfe in Trier"
        url = "/de/projects/trier-help/"
        weight = 6 
        parent = "projects"
    

    [[languages.de.menu.main]]
        name = "Galerie"
        url = "/de/gallery/"
        weight = 4

    [[languages.de.menu.main]]
        name = "Kalender"
        url = "/de/calendar/"
        weight = 5

    [[languages.de.menu.main]]
        identifier = "hilfe"
        name = "Hilfe"
        url = "/de/help"
        weight = 6

    [[languages.de.menu.main]]
        name = "Ich brauche Hilfe"
        url = "/de/help/need-help/"
        weight = 1   
        parent = "hilfe"
        
     [[languages.de.menu.main]]
        name = "Ich möchte helfen"
        url = "/de/help/want-help/"
        weight = 2  
        parent = "hilfe"

    [[languages.de.menu.main]]
        name = "Partner"
        url = "/de/partners/"
        weight = 7

    [[languages.de.menu.main]]
        name = "Kontakte"
        url = "/de/contacts"
        weight = 8

    [languages.en]
        contentDir = "content/en" #English
        weight = 3
        languageName = "English"
    [languages.en.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = "- a public platform created for the development and support of the Ukrainian cultural space in forced emigration."
        introSubtitle2 = "Why do we think this is important?"
        introSubtitle3 = "Speaking about Ukraine from the first person is a mission no less important than the work of diplomats at the highest levels. To show the Europeans that the Ukrainian war is not a scrap from a daily newspaper, not a short story on TV, but people - alive, freedom-loving, creative and strong. We do our best to support the fight for freedom and common democratic values."
        metaTitle = "Our goal:"
        metaSubtitle = "Our activity is to support Ukraine"
        metaSubtitle2 = "and not to forget about the war"
        calendarTitle = "Calendar of events"
        partnersTitle = "WE ARE SUPPORTED"
        partnersSubtitle ="We are grateful to the organizations that support us! For believing in our cause and walking side by side with us!"
        helpTitle = "Join us"
        aboutButton = "About us"
        partnersButton = "Partners"
        projectsButton = "Our projects"
        wantHelpButton = "I want to help"
        needHelpButton = "I need help"
        introPhoto = "/main-img.webp"
        logo = "/logo.svg"

    [[languages.en.menu.main]]
        name = "Main"
        url = "/en/"
        weight = 1

    [[languages.en.menu.main]]
        name = "About us"
        url = "/en/about/"
        weight = 2

    [[languages.en.menu.main]]
        identifier = "projects"
        name = "Our projects"
        url = "/en/projects/free-birds/"
        weight = 3

    [[languages.en.menu.main]]
        name = "Art space / art"
        url = "/en/projects/art/"
        weight = 1 
        parent = "projects"

    [[languages.en.menu.main]]
        name = "Catering/ Food courts"
        url = "/en/projects/catering/"
        weight = 2 
        parent = "projects"

    [[languages.en.menu.main]]
        name = "Creative team 'Free birds'"
        url = "/en/projects/free-birds/"
        weight = 3 
        parent = "projects"

    [[languages.en.menu.main]]
        name = "Educational projects"
        url = "/projects/educate-projects/"
        weight = 4 
        parent = "projects"

    [[languages.en.menu.main]]
        name = "Psychological help"
        url = "/en/projects/psych-help/"
        weight = 5 
        parent = "projects"

    [[languages.en.menu.main]]
        name = "Help in Trier"
        url = "/en/projects/trier-help/"
        weight = 6 
        parent = "projects"
    

    [[languages.en.menu.main]]
        name = "Gallery"
        url = "/en/gallery/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Calendar"
        url = "/en/calendar/"
        weight = 5

    [[languages.en.menu.main]]
        name = "Help"
        url = "/en/help"
        weight = 6

        [[languages.en.menu.main]]
        name = "I need help"
        url = "/en/help/need-help/"
        weight = 1   
        parent = "Help"
        
     [[languages.en.menu.main]]
        name = "I want to help"
        url = "/en/help/want-help/"
        weight = 2  
        parent = "Help"

    [[languages.en.menu.main]]
        name = "Partners"
        url = "/en/partners/"
        weight = 7

    [[languages.en.menu.main]]
        name = "Contacts"
        url = "/en/contacts"
        weight = 8

    [languages.fr]
        contentDir = "content/fr" #French
        weight = 4
        languageName = "Français"

    [languages.fr.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = "- une plate-forme publique créée pour le développement et le soutien de l'espace culturel ukrainien en émigration forcée."
        introSubtitle2 = "Pourquoi pensons-nous que c'est important?"
        introSubtitle3 = "Parler de l'Ukraine à la première personne est une mission non moins importante que le travail des diplomates au plus haut niveau. Pour montrer aux Européens que la guerre d'Ukraine n'est pas un bout de journal, pas une nouvelle à la télévision, mais des gens - vivants, épris de liberté, créatifs et forts. Nous faisons de notre mieux pour soutenir la lutte pour la liberté et les valeurs démocratiques communes."
        metaTitle = "Notre objectif:"
        metaSubtitle = "Notre activité est de soutenir l'Ukraine "
        metaSubtitle2 = "et ne pas oublier la guerre "
        calendarTitle = "Calendrier des événements"
        partnersTitle = "NOUS SOMMES ACCOMPAGNÉS"
        partnersSubtitle ="Nous remercions les organisations qui nous soutiennent ! Pour avoir cru en notre cause et marché à nos côtés !"
        helpTitle = "Rejoignez-nous"
        aboutButton = "À propos de nous"
        partnersButton = "Les partenaires"
        projectsButton = "Nos projets"
        wantHelpButton = "Je veux aider"
        needHelpButton = "J'ai besoin d'aide"
        introPhoto = "/main-img.webp"
        logo = "/logo.svg"

    [[languages.fr.menu.main]]
        name = "Page d'accueil"
        url = "/fr/"
        weight = 1

    [[languages.fr.menu.main]]
        name = "À propos de nous"
        url = "/fr/about/"
        weight = 2

    [[languages.fr.menu.main]]
        identifier = 'projects'
        name = "Nos projets"
        url = "/fr/projects/free-birds/"
        weight = 3

    [[languages.fr.menu.main]]
        name = "Espace artistique / art"
        url = "/fr/projects/art/"
        weight = 1 
        parent = "projects"

    [[languages.fr.menu.main]]
        name = "Restauration/ Foires alimentaires"
        url = "/fr/projects/catering/"
        weight = 2 
        parent = "projects"

    [[languages.fr.menu.main]]
        name = "Equipe créative 'Free Birds'"
        url = "/fr/projects/free-birds/"
        weight = 3 
        parent = "projects"

    [[languages.fr.menu.main]]
        name = "Projets pédagogiques"
        url = "/fr/projects/educate-projects/"
        weight = 4 
        parent = "projects"

    [[languages.fr.menu.main]]
        name = "Aide psychologique"
        url = "/fr/projects/psych-help/"
        weight = 5 
        parent = "projects"

    [[languages.fr.menu.main]]
        name = "Aide à Trèves"
        url = "/fr/projects/trier-help/"
        weight = 6 
        parent = "projects"
    

    [[languages.fr.menu.main]]
        name = "Galerie"
        url = "/fr/gallery/"
        weight = 4

    [[languages.fr.menu.main]]
        name = "Calendrier"
        url = "/fr/calendar/"
        weight = 5

    [[languages.fr.menu.main]]
        identifier = "aider"
        name = "Aider"
        url = "/fr/help/"
        weight = 6

    [[languages.fr.menu.main]]
        name = "J'ai besoin d'aide"
        url = "/fr/help/need-help/"
        weight = 1   
        parent = "aider"
        
     [[languages.fr.menu.main]]
        name = "Je veux aider"
        url = "/fr/help/want-help/"
        weight = 2  
        parent = "aider"

    [[languages.fr.menu.main]]
        name = "Les partenaires"
        url = "/fr/partners/"
        weight = 7

    [[languages.fr.menu.main]]
        name = "Contacts"
        url = "/fr/contacts"
        weight = 8

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Links to pages
  about='about'
  calendar='calendar'
  partners='partners'
  projects = 'projects/free-birds'
  helpMe = 'help/need-help'
  wantHelp = 'help/want-help'

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Ukrainer in Trier · All rights reserved"
  favicon = "/faviconWhite.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "projects"

  # The calendar events on the front page 
  calendarBundle = "events"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Громадське об'єднання"
  description = "Ми об'єднуємось разом, обмінюємось думками і ідеями - заради того, щоб бути сильнішими!"


  github = "https://github.com/"
  tikTok = "https://www.tiktok.com/@ua_in_trier"
  facebook = "https://www.facebook.com/ua.in.trier/"
  telegram = "https://t.me/ukrainer_in_trier"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
